version: '3.8'

services:
  appDatabase:
    image: postgres:14.8-alpine3.18
    container_name: postgresApp
    restart: always
    env_file:
      - ./.env
    volumes:
      - dbData:/var/lib/postgresql/data
    networks:
      - appNet
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # only for testing
    ports:
      - ${USER_PORT}:5432

  appBackend:
    depends_on:
      - appDatabase
    image: sebastianamg/testback:v1
    container_name: backendApp
    restart: always
    env_file:
      - ./.env
    networks:
      - appNet
    ports:
      - ${PORT}:5000
    # if not defined
    command: node dist/main

  # frontend:
  #   depends_on:
  #     - appBackend
  #   image: sebastianamg/testfront:v8
  #   container_name: frontendApp
  #   restart: always
  #   networks:
  #     - appNet
  #   environment:
  #     BACKEND_BASE_PATH: http://appBackend:${BACKEND_BASE_URL}
  #   ports:
  #     - ${FRONTEND_PORT}:2000
  #   # if not defined
  #   command: npm run preview

volumes:
  dbData:
    external: false

networks:
  appNet:
    external: false